### ISSUE TITLE
Unresolved reference when using top_level

### ISSUE THREAD

**Issue by BTWS2** [connorferster/forallpeople#12]
I want to use the units in the top level. The `mm` doesn't work and PyCharm says `m` and `mm` are an unresolved reference. 

What do I need to do different?

```Python
#%%
import handcalcs.render
import forallpeople as si
si.environment('default', top_level=True)

#%%
si.environment()

#%%
%%render
length = 4 * m
width = 3.5 * mm
area = length * width
area
```
![image](https://user-images.githubusercontent.com/56451049/91723019-6aa6dc80-eb9b-11ea-86d6-c262747efe71.png)

**Comment by connorferster** [comment]
Hi @BTWS2,

The default environment does not define `mm`. You can create a `mm` definition on the fly with `mm = 0.001*m`.

**Comment by BTWS2** [comment]
@connorferster Thank you for you response. I tried with *structural* now and it works, but the editor still doesn't find the reference (orange on the left hand side). I think the editor needs stubs.
![image](https://user-images.githubusercontent.com/56451049/92256901-9ea03b80-eed4-11ea-92b5-9e25bad00876.png)

**Comment by connorferster** [comment]
Hi @BTWS2, I have noticed this when I am working in VS Code, too. Because the variable are being created in the namespace dynamically, they are undetected by linters, e.g. `pylint`. Given that linters are static code checkers, there is no way for them to be able to detect this so they will always show the `forallpeople` unit variables as undefined. 

However, there is a way to let `pylint` know that certain variable names are dynamically created and will appear undefined. There are details [on this page](http://pylint.pycqa.org/en/latest/technical_reference/features.html) under the typechecker option of "generated-members".
