### ISSUE TITLE
Simple way to import all existing units in environment

### ISSUE THREAD

**Issue by BTWS2** [connorferster/forallpeople#13]
Now the `default` library only adds a handful of units. When solving/writing phisics equations, a lot of units are needed. Is there a way to import `all` existing units in the environment like this?

```Python
import forallpeople as si

si.environment('all', [top_level=False])
````

**Comment by connorferster** [comment]
Hi @BTWS2 Thanks for asking. There is a specific reason why this option does not exist: 

For "derived" units, those that are an alternative way of viewing combinations of SI units (e.g. N, J, W, etc.), the automatic representation of those units is controlled by their dimension, a NamedTuple that carries the dimensions like a vector. The dimensions are the keys in the environment dictionary and, like the Highlander, there can be only one. So, if one environment defines energy in Joules (like in the `default` environment) and the another defines energy in N*m (like in the `structural` environment), then they clash. So, for physics, I am wondering if it is common to refer to the same dimension in multiple ways. Does this happen where you would describe energy in Joules but, in another context of physics, describe energy as work, as N*m?

The overall intention with `forallpeople` is to create a units environment that describes one's typical calculating environment. Once it is set, you don't have to worry about it.

For "defined" units, units that are linear combinations of SI units (those with a factor, e.g. lb, ft), those units are also stored in a dictionary but the keys are the factors, as a float. A float is matched and then a look-up is done in the dimensions dictionary.

**Comment by BTWS2** [comment]
Thank you for the explanation. In some contexts both J, W and [kWh](https://en.wikipedia.org/wiki/Kilowatt-hour) are used. Is this possible with `forallpeople`?

**Comment by connorferster** [comment]
Hi @BTSW2, my apologies for this delay in response. Yes, J, W, and Wh are all able to be used in `forallpeople` simultaneously because they all have different dimensions (`J = kg*m*s**-2`, `W = kg*m**2*s**-3`, `kWh = kg*m**2*s-2`). The problem of "dimension clashing" only occurs when units have the same dimensions, e.g. `N*m = kg*m**2*s**-2` and `J = kg*m**2*s**-2`. In some contexts, one may think of energy as "N*m" and in another context think of energy as "J". For this reason, I have created this idea of a "unit environment" where units of a particular dimension are displayed as per the context that the user is working in. It is my assumption that users typically work in similar units environments, e.g. when I am working, I never think of units as Joules, only as N*m. However, for when a user may be working in a different context, then they can switch environments and have the unit dimensions display differently for that context.
