### ISSUE TITLE
Force different unit system for output

### ISSUE THREAD

**Issue by JBloss1517** [connorferster/forallpeople#14]
Is there a way to change the units that are returned from an equation? I am using the structural environment and have an equation where all of the parameters are in us imperial units (ksi, psi, inch) but the equation returns units of mm. The library is returning the correct dimension (length) but is no longer following the imperial system. Is there an easy way to change the output system?

![image](https://user-images.githubusercontent.com/50282451/92626106-1a143b00-f28f-11ea-8e01-99162bb63216.png)

**Comment by connorferster** [comment]
Yes, you can do:

```python
a = (A_s*f_y/(0.85*f_prime_c*b)).to('inch')
```

or

```python
a = A_s*f_y/(0.85*f_prime_c*b)
a = a.to('inch')
```

**Comment by JBloss1517** [comment]
Oh nice! Thank you. When working in conjunction with your handcalcs library, is there a more elegant solution to hiding the "to('inch')" part than to use

```python
%%render
a =A_s*f_y/(0.85*f_prime_c*b)
a = (a.to('inch'))
````

![image](https://user-images.githubusercontent.com/50282451/92647253-2f985d80-f2ad-11ea-9077-3495ea4d6ef6.png)
![image](https://user-images.githubusercontent.com/50282451/92647309-4a6ad200-f2ad-11ea-9871-13f3f11377c0.png)

**Comment by connorferster** [comment]
No, not yet :sob:

However, I am surprised that the factor did not carry through to produce a `inch` as the final result. I will look into that. The idea is that your result should be in `inch` without an extra conversion step. I think it has to do with the tolerance I set up on how factors carry. Because of floating point precision, every multiplicative operation between `Physical` instances with a `.factor` degrades the carried factor which reduces the likelihood that the factor at the end will be recognized and the `Physical` will be represented with the corresponding unit. 

This is something to fix. I will open a new issue in regards to this. Thank you for posting.

**Comment by JBloss1517** [comment]
Gotcha that makes sense. Thanks for creating such a great library!
