### ISSUE TITLE
Units removed after using sqrt from math module in handcalcs

### ISSUE THREAD

**Issue by michaellisitsa** [connorferster/forallpeople#19]
When placing an equation within a sqrt function from the math module, the units are not carried over correctly. Not sure if this needs to be fixed in the `forallpeople` codebase instead.

**How to reproduce**
```python
from math import sqrt

@handcalc(override="long")
def flange_yield(f_star_s_fl_mid,f_star_vf):
    f_star_comb = sqrt(f_star_s_fl_mid**2 + 3 * f_star_vf**2)
    return f_star_comb

flange_yield(...)
```
![image](https://user-images.githubusercontent.com/58811856/101275588-c1efc500-37fa-11eb-93af-4bde645adcc7.png)

**Expected Behaviour**
It should behave the same as using an exponent of 0.5, except with the square root notation. The above equation works fine if you use `**0.5`
```python
f_star_comb = (f_star_s_fl_mid**2 + 3 * f_star_vf**2)**0.5
```
![image](https://user-images.githubusercontent.com/58811856/101275659-56f2be00-37fb-11eb-8e43-553c56d3b449.png)

**Comment by connorferster** [comment]
Hi @michaellisitsa,

This is indeed a `forallpeople` issue. This behaviour is intentional because there is not (currently) a `__sqrt__` magic method in Python to define how custom objects behaves within a `math.sqrt(...)` function. 

When I was writing `forallpeople`, I was wondering how I could work with `math.sqrt` and have it behave the way I want. In then end, I found [this discussion on SO](https://stackoverflow.com/questions/53654178/python-square-root-for-class-instances). 

In `math.sqrt`, if the argument is not a `float` instance, `math.sqrt` calls `float(...)` on the argument first. I wrote `__float__` of `Physical` instances to return the "rendered" numeric value of the instance instead of returning the float stored in `.value`. This is why the result looks correct but just without the unit: I wanted `sqrt(25*lb)` to return `5` and I wanted `sqrt(25*kPa)` to return `5`, which I generally think is more intuitive (instead of `10.545403756211163` and `158.11388300841898`, which are the correct results when using `sqrt(<Physical>.value)`).

I have encountered this many times in my own scripts and here is what I do to work around it (based on the above SO discussion on re-defining `sqrt`):

![image](https://user-images.githubusercontent.com/38441489/103182227-ace8dd80-485e-11eb-99fc-802925c8a20a.png)
