### ISSUE TITLE
Pickling causes AttributeError

### ISSUE THREAD

**Issue by mortepau** [connorferster/forallpeople#29]
When we try to `pickle.loads` an si unit an AttributeError is raised.

```python
import forallpeople as si
import pickle

p = pickle.dumps(si.s) # or any other unit from si
pickle.loads(p) # Causes an AttributeError
```

Is this the intended behaviour?

**Comment by connorferster** [comment]
Hi @mortepau,

Thanks for bringing this up. I had never thought of pickling `Physical` instances! I have no idea what the intended behaviour is :) I just tried the pickling saving and loading process myself and I think I see what the problem is.

I just did some reading about pickling in the Python docs and ran across this bit: 

> The following types can be pickled:
>     * None, True, and False
>    * integers, floating point numbers, complex numbers
>    * strings, bytes, bytearrays
>    * tuples, lists, sets, and dictionaries containing only picklable objects
>    * functions defined at the top level of a module (using def, not lambda)
>    * built-in functions defined at the top level of a module
>    * classes that are defined at the top level of a module
>    * instances of such classes whose `__dict__` or the result of calling `__getstate__()` is picklable (see section Pickling Class Instances for details).

Specifically, the last point about `__dict__`. `Physical` instances do not have `__dict__` attributes. They instead use `__slots__` and cannot have attributes set on them after `__init__()` is run at the time of instantiation. I remember hearing on the PythonBytes.fm podcast a while ago that when objects are unpickled through `pickle.load()` that the objects' `__init__()` method _is not run_. This explains the behaviour.

Interestingly, I assumed that a `namedtuple` instance would demonstrate the same behaviour because they also use `__slots__` and are also immutable...however, I was able to pickle and unpickle a `namedtuple`...so more research is required. 

So, while this issue is not at the top of my list, I would like the a Physical instance to at least be consistent with a `namedtuple`, which was one of the prototype base types for `Physical` when I was designing them. It would likely be able to fix a couple of rare bugs that come up periodically. I will put this on the list for a future minor version release (cannot promise it will be the next one, though).

**Comment by mortepau** [comment]
Pickling a `Physical`  might be an odd use case. I currently use it when annotating data in a Dataframe for a web server, and I want to cache the Dataframe using the file-system which unfortunately relies on pickling.

I'm not sure if I can help with anything, but if you know of antyhing I can do let me know

**Comment by connorferster** [comment]
I have updated `Physical` so it can now be pickled. Please upgrade to the latest version for the fix.
