### ISSUE TITLE
Units not cancelling

### ISSUE THREAD

**Issue by ccaprani** [connorferster/forallpeople#50]
In the following, the result for `c` should be unitless:

```
from handcalcs import render, handcalc
import forallpeople
forallpeople.environment('structural',top_level = True)

%%render
a = 300*kN
b = 20*kN
c = a/sqrt(b**2)
```
but instead has units "kN".

Unfortunately, I don't have time now to get into a possible solution, but just recording it for now.

**Comment by connorferster** [comment]
Hi @ccaprani,

This is happening because of `math.sqrt`. The behaviour of `math.sqrt` is that it converts any non-float inputs to `float` and then performs the `sqrt` operation on the `float`.

The easiest way to control this behaviour is to define your own `sqrt` function which could be as simple as:
```python
def sqrt(x):
    return x**0.5
```
